/* Datos de productos compartidos entre páginas */
window.DULCE_PRODUCTS = [
    { id: 1, name: 'Torta Chantilly (Precio por kg)', category: 'Tortas', description: 'Bizcochuelo de vainilla húmedo, relleno de dulce de leche y crema chantilly.', image: 'images/torta-chantilly.svg', price: 19000 },
    { id: 2, name: 'Torta Forrada (Precio por kg)', category: 'Tortas', description: 'Elegante torta de varios pisos, forrada en fondant con detalles a elección.', image: 'images/torta-forrada.svg', price: 22000 },
    { id: 3, name: 'Chajá', category: 'Postres', description: 'Clásico postre con merengue, bizcochuelo, crema y duraznos. Aproximadamente 2kg', image: 'images/postre-chaja.svg', price: 35000 },
    { id: 4, name: 'Rogel', category: 'Postres', description: 'Capas de masa crocante con abundante dulce de leche y merengue italiano. Aproximadamente 2kg', image: 'images/postre-rogel.svg', price: 35000 },
    { id: 5, name: 'Cupcakes', category: 'Candy', description: 'Cupcakes de vainilla y chocolate con crema y relleno de colores.', image: 'images/cupcakes.svg', price: 1500 },
    { id: 6, name: 'Selva Negra', category: 'Postres', description: 'Postre alemán con capas de bizcocho de chocolate húmedo. Aproximadamente 2kg', image: 'images/selva-negra.svg', price: 35000 },
    { id: 7, name: 'Popcakes', category: 'Candy', description: 'Bocados de bizcochuelo y chocolate, perfectos para fiestas infantiles.', image: 'images/popcakes.svg', price: 1250 },
    { id: 8, name: 'Brownie', category: 'Postres', description: 'Brownie de chocolate intenso con una generosa capa de dulce de leche.', image: 'images/brownie.svg', price: 27000 },
    { id: 9, name: 'Vasos de Postres chico', category: 'Candy', description: 'Una selección de nuestros mejores postres en formato individual, ideales para eventos.', image: 'images/vasos-de-postres-chico.svg', price: 2000 },
    { id: 10, name: 'Vasos de Postres grande', category: 'Candy', description: 'Una selección de nuestros mejores postres en formato individual, ideales para eventos.', image: 'images/vasos-de-postres-grande.svg', price: 2500 },
    { id: 11, name: 'Pastafrola', category: 'Postres', description: 'Pastafrola clásica con masa suave y relleno a elección: membrillo, batata o dulce de leche, ideal para acompañar el mate o el café.', image: 'images/pastafrola.svg', price: 10000 },
    { id: 12, name: 'Tarta de Coco', category: 'Postres', description: 'Tarta de coco casera, húmeda y sabrosa, con un toque dulce irresistible, ideal para disfrutar en cualquier momento.', image: 'images/tarta-de-coco.svg', price: 15000 },
    { id: 13, name: 'Tarta de Chocolate', category: 'Postres', description: 'Tarta de chocolate suave y tentadora, con relleno cremoso y base crocante, perfecta para un antojo dulce.', image: 'images/tarta-de-chocolate.svg', price: 22000 },
    { id: 14, name: 'Tarta Frutal', category: 'Postres', description: 'Tarta frutal fresca y colorida, con base crocante y frutas seleccionadas, ideal como postre liviano y delicioso.', image: 'images/tarta-frutal.svg', price: 24000 },
    { id: 15, name: 'Tarta de Frutilla', category: 'Postres', description: 'Tarta de frutilla fresca, con relleno suave y frutillas naturales, dulce y liviana.', image: 'images/tarta-de-frutilla.svg', price: 24000 },
    { id: 16, name: 'Lemon Pie', category: 'Postres', description: 'Lemon pie clásico, con crema de limón suave y equilibrada, merengue delicado y base crocante.', image: 'images/lemon-pie.svg', price: 18000 },
    { id: 17, name: 'Petit Brownie', category: 'Candy', description: 'Petit brownie húmedo e intenso, con sabor profundo a chocolate, ideal para un gusto dulce individual.', image: 'images/petit-brownie.svg', price: 1100 },
    { id: 18, name: 'Oreos de Choco', category: 'Candy', description: 'Oreos bañadas en chocolate, crujientes por dentro y cubiertas con una capa dulce e irresistible.', image: 'images/oreos-de-choco.svg', price: 1500 },
    { id: 19, name: 'Paletas bañadas en chocolate', category: 'Candy', description: 'Paletas bañadas en chocolate, dulces y tentadoras, con una cobertura suave y deliciosa.', image: 'images/paletas-bañadas-en-chocolate.svg', price: 1750 },
    { id: 20, name: 'Alfajores de Chocolate', category: 'Candy', description: 'Alfajores de chocolate suaves y bien rellenos, con cobertura dulce y sabor equilibrado.', image: 'images/alfajores-de-chocolate.svg', price: 1000 },
    { id: 21, name: 'Alfajores de Maicena', category: 'Candy', description: 'Alfajores de maicena clásicos, rellenos con dulce de leche y espolvoreados con coco.', image: 'images/alfajores-de-maicena.svg', price: 500 },
    { id: 22, name: 'Pionono', category: 'Postres', description: 'Pionono dulce suave y esponjoso, relleno de dulce de leche y con sabor delicado, ideal para compartir.', image: 'images/pionono.svg', price: 10000 },

];
